#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Verifica informações do estudo alvo e indica capos com pendencia.

Usage:
    checkpend <identificador> [ <periodo> ]

Options:
    -v, --version

"""

import os

from docopt import docopt

args = docopt(__doc__)


def main():
    pass
        
if __name__ == '__main__':
    main()






