#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Cria ou recria arquivo de índices do banco de dados.

Usage:
    getline get <num_linha>
    getline list
    getline insert <string>

Options:
    --version

"""

import os
import itertools
import json
import sys

from subprocess import getoutput
from docopt import docopt
from python_modules.cli_tools import exhaust_generator_and_print, print_json_file_v2, load_json

app_root_folder = getoutput("cli-config read PASTA_RAIZ_DO_PROGRAMA")
forms_folder = os.sep.join([app_root_folder, "cli/formularios"])
formulario_atendimentos = os.sep.join([forms_folder, "form_atendimento.json"])

db_folder = getoutput("cli-config read PASTA_DE_DADOS")
index_folder = os.sep.join([db_folder, "indexados"])
arquivo_col_wid = os.sep.join([index_folder, "col_wid.json"])

args = docopt(__doc__)

test_file = '/home/danielc/clidados/atd.json'
col_wid = load_json(arquivo_col_wid)

def main():
    if args['get']:
        init_line = int(args['<num_linha>'])-1
        end_line = int(args['<num_linha>'])
        print_json_file_v2(test_file, formulario_atendimentos, col_wid, lines=(init_line, end_line))

    elif args['list']:
        print_json_file_v2(test_file, formulario_atendimentos, col_wid)

    elif args['insert']:
        with open(test_file, 'a') as atd:
            atd.write(args['<string>']+os.linesep)
        
        print(getoutput('wc -l < /home/danielc/clidados/atendimentos.json'))

    


if __name__ == '__main__':
    main()