#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Verifica informações do estudo alvo e indica capos com pendencia.

Usage:
    sort_forms 

Options:
    -v, --version

"""

import os

from docopt import docopt

from python_modules.cli_base import forms_folder
from python_modules.cli_tools import load_json, save_json, sort_dict, sort_questions_inner_dict

args = docopt(__doc__)

def main():
    os.chdir(forms_folder)
    forms = os.listdir('.')
    print(forms)
    for form in forms:
        formfile_path = os.sep.join([forms_folder, form])
        print(formfile_path)
        form_data = load_json(form)
        save_json(sort_dict(form_data), formfile_path)
    

        
if __name__ == '__main__':
    main()






